### PR TITLE
Adds Slack link and sign up form

### PR DESCRIPTION
**Pull request by JamesNix**
@neolytics Here's a Slack form similar to the Contact. Currently, it also adds an unintentional link in the navbar as well, but I'm too tired to figure out why right now. What @mshenfield did should work just fine so it might just be a matter of preference.

### CODE REVIEW

**Comment by neolytics** [comment]
I'll take a look at both commits tonight.  I'm inclined towards the form, but we've got build fails that need to be addressed on both ends.

**Comment by mshenfield** [comment]
@JamesNix  this is way better! B-t dubs I've fixed all those Travis CI build errors in pull request #78 - just link formatting issues.

**Comment by neolytics** [comment]
As far as I can tell the form works.  I assume this is sending to webmaster at codefornashville.org?  I evidently don't receive emails from that.

@beck410 Can you confirm that an email was sent? I tried to test it out a minute ago.

If that went through I'm happy with the PR.  Just need to merge in the travis updates and sync your branch.

**Comment by beck410** [comment]
yep i received an email from regarding adding a slack user through the webmaster email

**Comment by neolytics** [comment]
@JamesNix Would you mind updating this for the new design if there are any changes to be made?

Thanks man!

**Comment by neolytics** [comment]
Bump this would be really useful to have ready for the hack night this week

**Comment by beck410** [comment]
I'll have a look at it tonight and fix the travis CI errors

**Comment by JamesNix** [comment]
@neolytics @beck410 I merged with master and pushed again. I believe grid changes have been included. I can do more later if I need to.

**Comment by beck410** [comment]
awesome - Thanks @JamesNix  this is great for now - I'm going to merge it so its live

**Pull request merged**
