### PR TITLE
NDoCH and New Member link

### PR DESCRIPTION
**Pull request by enlore**
Tidied up the repo a bit as well.

### CODE REVIEW

**Comment by mshenfield** [comment]
This looks good to me. The clean-up is solid - the only thing debatable is moving the New Members link above the About section.  I don't have push access on this repo, pull in @beck410, she should be able to give the okay.

**Comment by beck410** [comment]
looks good to me - thanks for cleaning it up :)

**Comment by beck410** [comment]
:ship:

**Comment by beck410** [comment]
are you able to merge @enlore? if not just let me know and i'll merge it

**Comment by enlore** [comment]
I am able to merge.

**Pull request merged**
