### PR TITLE
sophicware logo

### PR DESCRIPTION
**Pull request by CharisseL**
Sophicware logo added to Sponsors
screen shot 2015-06-06 at 7 19 13 pm

### CODE REVIEW

**Comment by CharisseL** [comment]
@jcockhren i got back home & saw the above Failed message. I'm not familiar w/ this, never seen this failed/gold status before. Please advise.

**Comment by jcockhren** [comment]
@CharisseL They have a linter running. It runs tests that check for proper for style and best practice usage when the code is committed. Hit the (details) link.

**Comment by CharisseL** [comment]
@jcockhren got it. I added alt tags as it stated. hopefully that does it this time.

**Comment by beck410** [comment]
the socrata and hacknashville sites are getting 404 errors - if the links are working manually just merge it - travis builds have been buggy the last month or so

**Comment by jchapin** [comment]
I'll add Waffle, CTS, and MHRC logo to new tickets. Each gave us $200. They can go below the current roster of logos. NSS gave over $1k. Metro ITS as well at $500.

**Comment by CharisseL** [comment]
@jchapin are these additional logos available or would I need to pull from their respective sites, etc? and for clarity, that would be the addition of 4 logos (Waffle, CTS, MHRC, Metro ITS)?

**Comment by jchapin** [comment]
@CharisseL, opened up #111, #112, #113, #114.

**Comment by CharisseL** [comment]
@jchapin added logos. Fixes #110 #111 #112 #113 #114.
screen shot 2015-06-10 at 12 23 21 pm

**Comment by jchapin** [comment]
@CharisseL here's the MCC logo that I received straight from their staff.

mcc-trademark-logo-high-res

**Comment by jchapin** [comment]
I'll correct the errors that Travis is complaining about, but here's how the table looks now:

screen shot 2015-07-08 at 11 30 37 am

**Comment by jchapin** [comment]
There was one legit failure that hacknashville.com is offline. There were two other complaints about socrata.com being unavailable and nashploration.com timing out:

```
- ./_site/codeforamerica/brigade,/codeacross/2015/01/28/make-data-easy-to-find-and-use.html
  *  External link http://www.socrata.com/ failed: 403 No error
- ./_site/codeforamerica/brigade/2014/11/05/september-meeting-notes.html
  *  External link http://nashploration.com/ failed: got a time out
- ./_site/codeforamerica/brigade/2014/11/24/hack-nashville-blog-post.html
  *  External link http://www.hacknashville.com/ failed: 403 No error
```

This seems safe to merge. I wonder if the maintainers of Nashploration renewed their domain name or took their app down.

**Pull request merged**
