### PR TITLE
UX Improvements for New Member page

### PR DESCRIPTION
**Pull request by enlore**
Been collecting UX feedback from new peeps. Made a few tweaks to improve usability and reduce frustration.

Octocat!
screen shot 2016-04-15 at 9 28 08 pm

Taco!
screen shot 2016-04-15 at 9 28 22 pm

### CODE REVIEW

**Comment by enlore** [comment]
@beck410 
@mshenfield

**Comment by ebmshenfield** [comment]
:+1: this looks great, and appreciate not showing the popup as much.

**Comment by ebbeck** [comment]
not a fan of inline styles but i won't hold it up just for that 🚢

**Comment by enlore** [comment]
promise I'll refactor those before too long!

**Pull request merged**
