### PR TITLE
Replaced slack form with slackin link

### PR DESCRIPTION
**Pull request by mshenfield**
slackin (http://rauchg.com/slackin/) is an automatic Slack signup form that lets user's join the Slack page with a single click. I'm hosting an endpoint on my Heroku account at https://nashville-brigade-slackin.herokuapp.com/. I replaced the link to the Slack form with a link to this new endpoint.

This endpoint also exposes badges we can post for individual channels we can add to README of projects (a la Travis CI badges). Haven't done any work on it yet, but it could be a cool addition and help users get involved in the discussion more quickly.

### CODE REVIEW

**Comment by beck410** [comment]
I feel like the travis-ci build failures is my fault from a previous merge - i'm going to try and fix it before merging this in

**Comment by mshenfield** [comment]
Right on. Let me know if there's anything I can do to help.

**Comment by beck410** [comment]
ok build errors should be fixed - pull down changes before merging

**Comment by mshenfield** [comment]
Pulled in the changes - thanks @beck410. Should be good to go.

**Pull request merged**
