### PR TITLE
#96/Tutorials Page

### PR DESCRIPTION
**Pull request by rocketpastsix**
Added the markdown for a tutorial for Vagrant. Issue #96 on the Code
For Nashville Github Repo

### CODE REVIEW

**Comment by beck410** [comment]
great - i'll pull it down soon and check out the error :)

Thanks

**Comment by rocketpastsix** [comment]
Thats interesting, what could the error be?

**Comment by beck410** [comment]
i think its trying to run a localhost link in the tut

**Comment by rocketpastsix** [comment]
Makes sense. Anyways, Ill be around in case its something I need to fix on my end :)

**Comment by beck410** [comment]
I't just going to merge it in and fix the error through master - Github is being weird and not letting me edit :)

**Pull request merged**
