### PR TITLE
New design

### PR DESCRIPTION
**Pull request by beck410**
@neolytics  @jchapin  
Finished most of v2.0 of website - still a lot of little things to get done but may as well put it up - could you guys pull it down and check for any major problems

### CODE REVIEW

**Comment by neolytics** [comment]
I'll see what I can do.  Need to setup jekyll etc.

On Tue, Mar 10, 2015 at 7:39 PM, Rebecca Cronin-Dixon <
notifications@github.com> wrote:

> @neolytics <https://github.com/neolytics> @jchapin
> <https://github.com/jchapin>
>
> Finished most of v2.0 of website - still a lot of little things to get
> done but may as well put it up - could you guys pull it down and check for
> any major problems
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>
> https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73
> Commit Summary
>
>    - header design finished
>    - header responsive
>    - home page design finished
>    - fixed footer design
>    - changed menu bg color and fixed responsive contact icons
>    - added files to ignore
>    - added design to homepage
>    - added styling for blog
>    - styled contact page
>    - styled projects page
>    - fixed contact styling
>    - changed max-width for row
>    - added styling to layout and contact form
>
> File Changes
>
>    - *M* .gitignore
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-0>
>    (2)
>    - *M* _includes/about.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-1>
>    (7)
>    - *M* _includes/contact_icons.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-2>
>    (74)
>    - *M* _includes/footer.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-3>
>    (15)
>    - *M* _includes/head.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-4>
>    (6)
>    - *M* _includes/header.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-5>
>    (59)
>    - *M* _includes/recent_blogs.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-6>
>    (2)
>    - *M* _layouts/default.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-7>
>    (14)
>    - *D* _sass/_base.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-8>
>    (207)
>    - *A* _sass/_blog.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-9>
>    (14)
>    - *A* _sass/_contact.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-10>
>    (23)
>    - *A* _sass/_footer.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-11>
>    (7)
>    - *A* _sass/_header.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-12>
>    (136)
>    - *A* _sass/_home.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-13>
>    (33)
>    - *M* _sass/_layout.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-14>
>    (268)
>    - *A* _sass/_projects.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-15>
>    (13)
>    - *D* _sass/_syntax-highlighting.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-16>
>    (67)
>    - *D* _sass/bootstrap.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-17>
>    (50)
>    - *D* _sass/bootstrap/_alerts.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-18>
>    (68)
>    - *D* _sass/bootstrap/_badges.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-19>
>    (57)
>    - *D* _sass/bootstrap/_breadcrumbs.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-20>
>    (26)
>    - *D* _sass/bootstrap/_button-groups.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-21>
>    (240)
>    - *D* _sass/bootstrap/_buttons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-22>
>    (157)
>    - *D* _sass/bootstrap/_carousel.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-23>
>    (243)
>    - *D* _sass/bootstrap/_close.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-24>
>    (35)
>    - *D* _sass/bootstrap/_code.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-25>
>    (68)
>    - *D* _sass/bootstrap/_component-animations.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-26>
>    (35)
>    - *D* _sass/bootstrap/_dropdowns.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-27>
>    (215)
>    - *D* _sass/bootstrap/_forms.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-28>
>    (538)
>    - *D* _sass/bootstrap/_glyphicons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-29>
>    (237)
>    - *D* _sass/bootstrap/_grid.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-30>
>    (84)
>    - *D* _sass/bootstrap/_input-groups.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-31>
>    (166)
>    - *D* _sass/bootstrap/_jumbotron.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-32>
>    (48)
>    - *D* _sass/bootstrap/_labels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-33>
>    (66)
>    - *D* _sass/bootstrap/_list-group.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-34>
>    (131)
>    - *D* _sass/bootstrap/_media.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-35>
>    (56)
>    - *D* _sass/bootstrap/_mixins.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-36>
>    (39)
>    - *D* _sass/bootstrap/_modals.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-37>
>    (150)
>    - *D* _sass/bootstrap/_navbar.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-38>
>    (659)
>    - *D* _sass/bootstrap/_navs.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-39>
>    (242)
>    - *D* _sass/bootstrap/_normalize.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-40>
>    (425)
>    - *D* _sass/bootstrap/_pager.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-41>
>    (55)
>    - *D* _sass/bootstrap/_pagination.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-42>
>    (88)
>    - *D* _sass/bootstrap/_panels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-43>
>    (243)
>    - *D* _sass/bootstrap/_popovers.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-44>
>    (133)
>    - *D* _sass/bootstrap/_print.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-45>
>    (101)
>    - *D* _sass/bootstrap/_progress-bars.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-46>
>    (105)
>    - *D* _sass/bootstrap/_responsive-embed.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-47>
>    (34)
>    - *D* _sass/bootstrap/_responsive-utilities.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-48>
>    (174)
>    - *D* _sass/bootstrap/_scaffolding.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-49>
>    (150)
>    - *D* _sass/bootstrap/_tables.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-50>
>    (233)
>    - *D* _sass/bootstrap/_theme.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-51>
>    (258)
>    - *D* _sass/bootstrap/_thumbnails.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-52>
>    (38)
>    - *D* _sass/bootstrap/_tooltip.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-53>
>    (95)
>    - *D* _sass/bootstrap/_type.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-54>
>    (304)
>    - *D* _sass/bootstrap/_utilities.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-55>
>    (57)
>    - *D* _sass/bootstrap/_variables.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-56>
>    (850)
>    - *D* _sass/bootstrap/_wells.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-57>
>    (29)
>    - *D* _sass/bootstrap/bootstrap.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-58>
>    (50)
>    - *D* _sass/bootstrap/mixins/_alerts.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-59>
>    (14)
>    - *D* _sass/bootstrap/mixins/_background-variant.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-60>
>    (11)
>    - *D* _sass/bootstrap/mixins/_border-radius.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-61>
>    (18)
>    - *D* _sass/bootstrap/mixins/_buttons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-62>
>    (50)
>    - *D* _sass/bootstrap/mixins/_center-block.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-63>
>    (7)
>    - *D* _sass/bootstrap/mixins/_clearfix.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-64>
>    (22)
>    - *D* _sass/bootstrap/mixins/_forms.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-65>
>    (84)
>    - *D* _sass/bootstrap/mixins/_gradients.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-66>
>    (58)
>    - *D* _sass/bootstrap/mixins/_grid-framework.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-67>
>    (81)
>    - *D* _sass/bootstrap/mixins/_grid.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-68>
>    (122)
>    - *D* _sass/bootstrap/mixins/_hide-text.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-69>
>    (21)
>    - *D* _sass/bootstrap/mixins/_image.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-70>
>    (34)
>    - *D* _sass/bootstrap/mixins/_labels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-71>
>    (12)
>    - *D* _sass/bootstrap/mixins/_list-group.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-72>
>    (31)
>    - *D* _sass/bootstrap/mixins/_nav-divider.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-73>
>    (10)
>    - *D* _sass/bootstrap/mixins/_nav-vertical-align.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-74>
>    (9)
>    - *D* _sass/bootstrap/mixins/_opacity.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-75>
>    (8)
>    - *D* _sass/bootstrap/mixins/_pagination.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-76>
>    (23)
>    - *D* _sass/bootstrap/mixins/_panels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-77>
>    (24)
>    - *D* _sass/bootstrap/mixins/_progress-bar.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-78>
>    (10)
>    - *D* _sass/bootstrap/mixins/_reset-filter.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-79>
>    (8)
>    - *D* _sass/bootstrap/mixins/_resize.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-80>
>    (6)
>    - *D* _sass/bootstrap/mixins/_responsive-visibility.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-81>
>    (21)
>    - *D* _sass/bootstrap/mixins/_size.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-82>
>    (10)
>    - *D* _sass/bootstrap/mixins/_tab-focus.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-83>
>    (9)
>    - *D* _sass/bootstrap/mixins/_table-row.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-84>
>    (28)
>    - *D* _sass/bootstrap/mixins/_text-emphasis.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-85>
>    (11)
>    - *D* _sass/bootstrap/mixins/_text-overflow.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-86>
>    (8)
>    - *D* _sass/bootstrap/mixins/_vendor-prefixes.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-87>
>    (219)
>    - *M* blog.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-88>
>    (4)
>    - *A* css/foundation/.bower.json
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-89>
>    (33)
>    - *A* css/foundation/bower.json
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-90>
>    (23)
>    - *A* css/foundation/css/foundation.css
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-91>
>    (6155)
>    - *A* css/foundation/css/foundation.css.map
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-92>
>    (7)
>    - *A* css/foundation/css/normalize.css
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-93>
>    (359)
>    - *A* css/foundation/css/normalize.css.map
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-94>
>    (7)
>    - *A* css/foundation/js/foundation.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-95>
>    (6097)
>    - *A* css/foundation/js/foundation.min.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-96>
>    (4)
>    - *A* css/foundation/js/foundation/foundation.abide.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-97>
>    (340)
>    - *A* css/foundation/js/foundation/foundation.accordion.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-98>
>    (67)
>    - *A* css/foundation/js/foundation/foundation.alert.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-99>
>    (43)
>    - *A* css/foundation/js/foundation/foundation.clearing.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-100>
>    (556)
>    - *A* css/foundation/js/foundation/foundation.dropdown.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-101>
>    (448)
>    - *A* css/foundation/js/foundation/foundation.equalizer.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-102>
>    (77)
>    - *A* css/foundation/js/foundation/foundation.interchange.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-103>
>    (354)
>    - *A* css/foundation/js/foundation/foundation.joyride.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-104>
>    (932)
>    - *A* css/foundation/js/foundation/foundation.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-105>
>    (703)
>    - *A* css/foundation/js/foundation/foundation.magellan.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-106>
>    (203)
>    - *A* css/foundation/js/foundation/foundation.offcanvas.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-107>
>    (152)
>    - *A* css/foundation/js/foundation/foundation.orbit.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-108>
>    (476)
>    - *A* css/foundation/js/foundation/foundation.reveal.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-109>
>    (471)
>    - *A* css/foundation/js/foundation/foundation.slider.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-110>
>    (263)
>    - *A* css/foundation/js/foundation/foundation.tab.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-111>
>    (237)
>    - *A* css/foundation/js/foundation/foundation.tooltip.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-112>
>    (307)
>    - *A* css/foundation/js/foundation/foundation.topbar.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-113>
>    (452)
>    - *A* css/foundation/js/vendor/fastclick.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-114>
>    (8)
>    - *A* css/foundation/js/vendor/jquery.cookie.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-115>
>    (8)
>    - *A* css/foundation/js/vendor/jquery.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-116>
>    (26)
>    - *A* css/foundation/js/vendor/modernizr.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-117>
>    (8)
>    - *A* css/foundation/js/vendor/placeholder.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-118>
>    (2)
>    - *A* css/foundation/scss/foundation.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-119>
>    (45)
>    - *A* css/foundation/scss/foundation/_functions.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-120>
>    (146)
>    - *A* css/foundation/scss/foundation/_settings.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-121>
>    (1467)
>    - *A* css/foundation/scss/foundation/components/_accordion.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-122>
>    (157)
>    - *A* css/foundation/scss/foundation/components/_alert-boxes.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-123>
>    (128)
>    - *A* css/foundation/scss/foundation/components/_block-grid.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-124>
>    (133)
>    - *A* css/foundation/scss/foundation/components/_breadcrumbs.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-125>
>    (132)
>    - *A* css/foundation/scss/foundation/components/_button-groups.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-126>
>    (200)
>    - *A* css/foundation/scss/foundation/components/_buttons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-127>
>    (260)
>    - *A* css/foundation/scss/foundation/components/_clearing.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-128>
>    (256)
>    - *A* css/foundation/scss/foundation/components/_dropdown-buttons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-129>
>    (131)
>    - *A* css/foundation/scss/foundation/components/_dropdown.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-130>
>    (262)
>    - *A* css/foundation/scss/foundation/components/_flex-video.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-131>
>    (51)
>    - *A* css/foundation/scss/foundation/components/_forms.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-132>
>    (577)
>    - *A* css/foundation/scss/foundation/components/_global.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-133>
>    (480)
>    - *A* css/foundation/scss/foundation/components/_grid.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-134>
>    (289)
>    - *A* css/foundation/scss/foundation/components/_icon-bar.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-135>
>    (359)
>    - *A* css/foundation/scss/foundation/components/_inline-lists.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-136>
>    (57)
>    - *A* css/foundation/scss/foundation/components/_joyride.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-137>
>    (222)
>    - *A* css/foundation/scss/foundation/components/_keystrokes.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-138>
>    (61)
>    - *A* css/foundation/scss/foundation/components/_labels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-139>
>    (106)
>    - *A* css/foundation/scss/foundation/components/_magellan.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-140>
>    (34)
>    - *A* css/foundation/scss/foundation/components/_offcanvas.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-141>
>    (515)
>    - *A* css/foundation/scss/foundation/components/_orbit.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-142>
>    (368)
>    - *A* css/foundation/scss/foundation/components/_pagination.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-143>
>    (162)
>    - *A* css/foundation/scss/foundation/components/_panels.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-144>
>    (101)
>    - *A* css/foundation/scss/foundation/components/_pricing-tables.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-145>
>    (150)
>    - *A* css/foundation/scss/foundation/components/_progress-bars.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-146>
>    (79)
>    - *A* css/foundation/scss/foundation/components/_range-slider.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-147>
>    (170)
>    - *A* css/foundation/scss/foundation/components/_reveal.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-148>
>    (209)
>    - *A* css/foundation/scss/foundation/components/_side-nav.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-149>
>    (116)
>    - *A* css/foundation/scss/foundation/components/_split-buttons.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-150>
>    (203)
>    - *A* css/foundation/scss/foundation/components/_sub-nav.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-151>
>    (122)
>    - *A* css/foundation/scss/foundation/components/_switches.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-152>
>    (238)
>    - *A* css/foundation/scss/foundation/components/_tables.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-153>
>    (135)
>    - *A* css/foundation/scss/foundation/components/_tabs.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-154>
>    (125)
>    - *A* css/foundation/scss/foundation/components/_thumbs.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-155>
>    (66)
>    - *A* css/foundation/scss/foundation/components/_toolbar.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-156>
>    (72)
>    - *A* css/foundation/scss/foundation/components/_tooltips.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-157>
>    (142)
>    - *A* css/foundation/scss/foundation/components/_top-bar.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-158>
>    (696)
>    - *A* css/foundation/scss/foundation/components/_type.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-159>
>    (464)
>    - *A* css/foundation/scss/foundation/components/_visibility.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-160>
>    (474)
>    - *A* css/foundation/scss/normalize.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-161>
>    (427)
>    - *M* css/main.scss
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-162>
>    (60)
>    - *M* events.md
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-163>
>    (12)
>    - *A* img/cfn-placeholder.jpg
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-164>
>    (0)
>    - *A* img/cfn_logo.jpg
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-165>
>    (0)
>    - *A* img/skyline.jpg
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-166>
>    (0)
>    - *M* index.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-167>
>    (25)
>    - *A* js/menu.js
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-168>
>    (10)
>    - *M* projects.html
>    <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73/files#diff-169>
>    (25)
>
> Patch Links:
>
>    -
>    https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73.patch
>    -
>    https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-for-nashville/code-for-nashville.github.io/pull/73>
> .
>



-- 
Jon Staples M.S.2

[Data Scientist | NextGxDx | www.nextgxdx.com]

**Comment by neolytics** [comment]
I am working on setting up an environment with Jekyll now.  Will have to familiarize myself with it and travis, but the builds failed.

**Comment by beck410** [comment]
thats so weird when i uploaded it was passing

**Comment by neolytics** [comment]
@beck410 You know, when I think about it, the only stuff that really needs to be changed to the design or slight formatting issues.  I have no issue with pushing this soon.  Maybe at the management meeting we can discuss a strategic way to announce the new design, maybe coinciding with a hack night announcement?

**Comment by beck410** [comment]
That would be great to push it soon as i'd like just to add the new tutorials page to the new design. Hopefully with the new design up people will want to add to it more.

**Comment by beck410** [comment]
@neolytics yay finally fixed the build errors - should i go ahead and merge?

**Pull request merged**
